resources:
  - ../base
namePrefix: dev-

commonLabels:
  env: dev

images:
  - name: nginx
    newTag: alpine

patchesStrategicMerge:
  - resources_limits_patch.yaml

configMapGenerator:
  - name: app-envs
    behavior: merge
    envs:
      - app.env